#############################################################################
# Makefile for building: tbclient
# Generated by qmake (2.01a) (Qt 4.7.4) on: ?? 5? 18 13:41:44 2013
# Project:  tbclient.pro
# Template: app
# Command: d:\qtsdk\symbian\sdks\symbiansr1qt474\bin\qmake.exe -spec ..\..\QtSDK\Symbian\SDKs\SymbianSR1Qt474\mkspecs\symbian-sbsv2 CONFIG+=release -after  OBJECTS_DIR=obj MOC_DIR=moc UI_DIR=ui RCC_DIR=rcc -o bld.inf tbclient.pro
#############################################################################

MAKEFILE          = Makefile
QMAKE             = d:\qtsdk\symbian\sdks\symbiansr1qt474\bin\qmake.exe
DEL_FILE          = del /q 2> NUL
DEL_DIR           = rmdir
CHK_DIR_EXISTS    = if not exist
MKDIR             = mkdir
MOVE              = move
DEBUG_PLATFORMS   = winscw gcce armv5 armv6
RELEASE_PLATFORMS = gcce armv5 armv6
MAKE              = make
SBS               = sbs

DEFINES	 = -DSYMBIAN -DUNICODE -DQT_KEYPAD_NAVIGATION -DQT_SOFTKEYS_ENABLED -DQT_USE_MATH_H_FLOATS -DIN_APP_PURCHASE -DIN_APP_PURCHASE_DEBUG -DQVIBRA -DVER="1.6.2" -DQ_COMPONENTS_SYMBIAN -DHAVE_MOBILITY -DQT_NO_DEBUG -DQT_DECLARATIVE_LIB -DQT_WEBKIT_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
INCPATH	 =  -I"D:/QtSDK/Symbian/SDKs/SymbianSR1Qt474/include/QtCore"  -I"D:/QtSDK/Symbian/SDKs/SymbianSR1Qt474/include/QtNetwork"  -I"D:/QtSDK/Symbian/SDKs/SymbianSR1Qt474/include/QtGui"  -I"D:/QtSDK/Symbian/SDKs/SymbianSR1Qt474/include/QtWebKit"  -I"D:/QtSDK/Symbian/SDKs/SymbianSR1Qt474/include/QtDeclarative"  -I"D:/QtSDK/Symbian/SDKs/SymbianSR1Qt474/include"  -I"D:/QtSDK/Symbian/SDKs/SymbianSR1Qt474/mkspecs/common/symbian"  -I"D:/QtSDK/Symbian/SDKs/SymbianSR1Qt474/epoc32/include"  -I"D:/QtSDK/Symbian/SDKs/SymbianSR1Qt474/epoc32/include/stdapis"  -I"D:/QtSDK/Symbian/SDKs/SymbianSR1Qt474/epoc32/include/stdapis/sys"  -I"D:/QtProject/tbclient/src"  -I"D:/QtProject/tbclient/QVibra"  -I"D:/QtProject/tbclient/qmlapplicationviewer"  -I"D:/QtSDK/Symbian/SDKs/SymbianSR1Qt474/epoc32/include/mw"  -I"D:/QtSDK/Symbian/SDKs/SymbianSR1Qt474/epoc32/include/platform/mw"  -I"D:/QtSDK/Symbian/SDKs/SymbianSR1Qt474/epoc32/include/platform"  -I"D:/QtSDK/Symbian/SDKs/SymbianSR1Qt474/epoc32/include/app"  -I"D:/QtSDK/Symbian/SDKs/SymbianSR1Qt474/epoc32/include/platform/app"  -I"D:/QtSDK/Symbian/SDKs/SymbianSR1Qt474/epoc32/include/platform/loc"  -I"D:/QtSDK/Symbian/SDKs/SymbianSR1Qt474/epoc32/include/platform/mw/loc"  -I"D:/QtSDK/Symbian/SDKs/SymbianSR1Qt474/epoc32/include/platform/app/loc"  -I"D:/QtSDK/Symbian/SDKs/SymbianSR1Qt474/epoc32/include/platform/loc/sc"  -I"D:/QtSDK/Symbian/SDKs/SymbianSR1Qt474/epoc32/include/platform/mw/loc/sc"  -I"D:/QtSDK/Symbian/SDKs/SymbianSR1Qt474/epoc32/include/platform/app/loc/sc"  -I"D:/QtSDK/Symbian/SDKs/SymbianSR1Qt474/epoc32/include/stdapis/stlportv5"  -I"D:/QtSDK/Symbian/SDKs/SymbianSR1Qt474/include/QtXmlPatterns"  -I"D:/QtProject/tbclient/moc"  -I"D:/QtProject/tbclient/qiap"  -I"D:/QtProject/tbclient"  -I"D:/QtProject/tbclient/rcc"  -I"D:/QtProject/tbclient/ui" 
first: default

all: debug release

default: debug-winscw
qmake:
	$(QMAKE) "D:/QtProject/tbclient/tbclient.pro"  -spec ..\..\QtSDK\Symbian\SDKs\SymbianSR1Qt474\mkspecs\symbian-sbsv2 CONFIG+=release -after  OBJECTS_DIR=obj MOC_DIR=moc UI_DIR=ui RCC_DIR=rcc

bld.inf: D:/QtProject/tbclient/tbclient.pro
	$(QMAKE) "D:/QtProject/tbclient/tbclient.pro"  -spec ..\..\QtSDK\Symbian\SDKs\SymbianSR1Qt474\mkspecs\symbian-sbsv2 CONFIG+=release -after  OBJECTS_DIR=obj MOC_DIR=moc UI_DIR=ui RCC_DIR=rcc

d:\QtProject\tbclient\tbclient.loc: D:/QtProject/tbclient/i18n/tbclient_zh.ts
	$(QMAKE) "D:/QtProject/tbclient/tbclient.pro"  -spec ..\..\QtSDK\Symbian\SDKs\SymbianSR1Qt474\mkspecs\symbian-sbsv2 CONFIG+=release -after  OBJECTS_DIR=obj MOC_DIR=moc UI_DIR=ui RCC_DIR=rcc

debug: d:\QtProject\tbclient\tbclient.loc bld.inf
	$(SBS) -c winscw_udeb.mwccinc -c arm.v5.udeb.gcce4_4_1 -c arm.v6.udeb.gcce4_4_1
clean-debug: bld.inf
	$(SBS) reallyclean --toolcheck=off -c winscw_udeb.mwccinc -c arm.v5.udeb.gcce4_4_1 -c arm.v6.udeb.gcce4_4_1
freeze-debug: bld.inf
	$(SBS) freeze -c winscw_udeb.mwccinc -c arm.v5.udeb.gcce4_4_1 -c arm.v6.udeb.gcce4_4_1
release: d:\QtProject\tbclient\tbclient.loc bld.inf
	$(SBS) -c arm.v5.urel.gcce4_4_1 -c arm.v6.urel.gcce4_4_1
clean-release: bld.inf
	$(SBS) reallyclean --toolcheck=off -c arm.v5.urel.gcce4_4_1 -c arm.v6.urel.gcce4_4_1
freeze-release: bld.inf
	$(SBS) freeze -c arm.v5.urel.gcce4_4_1 -c arm.v6.urel.gcce4_4_1

debug-winscw: d:\QtProject\tbclient\tbclient.loc bld.inf
	$(SBS) -c winscw_udeb.mwccinc
clean-debug-winscw: bld.inf
	$(SBS) reallyclean -c winscw_udeb.mwccinc
freeze-debug-winscw: bld.inf
	$(SBS) freeze -c winscw_udeb.mwccinc
debug-gcce: d:\QtProject\tbclient\tbclient.loc bld.inf
	$(SBS) -c arm.v5.udeb.gcce4_4_1
clean-debug-gcce: bld.inf
	$(SBS) reallyclean -c arm.v5.udeb.gcce4_4_1
freeze-debug-gcce: bld.inf
	$(SBS) freeze -c arm.v5.udeb.gcce4_4_1
debug-armv5: d:\QtProject\tbclient\tbclient.loc bld.inf
	$(SBS) -c armv5_udeb
clean-debug-armv5: bld.inf
	$(SBS) reallyclean -c armv5_udeb
freeze-debug-armv5: bld.inf
	$(SBS) freeze -c armv5_udeb
debug-armv6: d:\QtProject\tbclient\tbclient.loc bld.inf
	$(SBS) -c armv6_udeb
clean-debug-armv6: bld.inf
	$(SBS) reallyclean -c armv6_udeb
freeze-debug-armv6: bld.inf
	$(SBS) freeze -c armv6_udeb
release-gcce: d:\QtProject\tbclient\tbclient.loc bld.inf
	$(SBS) -c arm.v5.urel.gcce4_4_1
clean-release-gcce: bld.inf
	$(SBS) reallyclean -c arm.v5.urel.gcce4_4_1
freeze-release-gcce: bld.inf
	$(SBS) freeze -c arm.v5.urel.gcce4_4_1
release-armv5: d:\QtProject\tbclient\tbclient.loc bld.inf
	$(SBS) -c armv5_urel
clean-release-armv5: bld.inf
	$(SBS) reallyclean -c armv5_urel
freeze-release-armv5: bld.inf
	$(SBS) freeze -c armv5_urel
release-armv6: d:\QtProject\tbclient\tbclient.loc bld.inf
	$(SBS) -c armv6_urel
clean-release-armv6: bld.inf
	$(SBS) reallyclean -c armv6_urel
freeze-release-armv6: bld.inf
	$(SBS) freeze -c armv6_urel
debug-armv5-gcce4.4.1: d:\QtProject\tbclient\tbclient.loc bld.inf
	$(SBS) -c arm.v5.udeb.gcce4_4_1
clean-debug-armv5-gcce4.4.1: bld.inf
	$(SBS) reallyclean -c arm.v5.udeb.gcce4_4_1
freeze-debug-armv5-gcce4.4.1: bld.inf
	$(SBS) freeze -c arm.v5.udeb.gcce4_4_1
release-armv5-gcce4.4.1: d:\QtProject\tbclient\tbclient.loc bld.inf
	$(SBS) -c arm.v5.urel.gcce4_4_1
clean-release-armv5-gcce4.4.1: bld.inf
	$(SBS) reallyclean -c arm.v5.urel.gcce4_4_1
freeze-release-armv5-gcce4.4.1: bld.inf
	$(SBS) freeze -c arm.v5.urel.gcce4_4_1
debug-armv6-gcce4.4.1: d:\QtProject\tbclient\tbclient.loc bld.inf
	$(SBS) -c arm.v6.udeb.gcce4_4_1
clean-debug-armv6-gcce4.4.1: bld.inf
	$(SBS) reallyclean -c arm.v6.udeb.gcce4_4_1
freeze-debug-armv6-gcce4.4.1: bld.inf
	$(SBS) freeze -c arm.v6.udeb.gcce4_4_1
release-armv6-gcce4.4.1: d:\QtProject\tbclient\tbclient.loc bld.inf
	$(SBS) -c arm.v6.urel.gcce4_4_1
clean-release-armv6-gcce4.4.1: bld.inf
	$(SBS) reallyclean -c arm.v6.urel.gcce4_4_1
freeze-release-armv6-gcce4.4.1: bld.inf
	$(SBS) freeze -c arm.v6.urel.gcce4_4_1

export: bld.inf
	$(SBS) export -c winscw_udeb.mwccinc -c arm.v5.udeb.gcce4_4_1 -c arm.v6.udeb.gcce4_4_1 -c arm.v5.urel.gcce4_4_1 -c arm.v6.urel.gcce4_4_1

cleanexport: bld.inf
	$(SBS) cleanexport -c winscw_udeb.mwccinc -c arm.v5.udeb.gcce4_4_1 -c arm.v6.udeb.gcce4_4_1 -c arm.v5.urel.gcce4_4_1 -c arm.v6.urel.gcce4_4_1

freeze: freeze-release

check: first

run:
	call D:/QtSDK/Symbian/SDKs/SymbianSR1Qt474/epoc32/release/winscw/udeb/tbclient.exe $(QT_RUN_OPTIONS)

runonphone: sis
	runonphone $(QT_RUN_ON_PHONE_OPTIONS) --sis tbclient.sis tbclient.exe $(QT_RUN_OPTIONS)

tbclient_template.pkg: D:/QtProject/tbclient/i18n/tbclient_zh.ts D:/QtProject/tbclient/tbclient.pro
	$(MAKE) -f $(MAKEFILE) qmake

tbclient_installer.pkg: D:/QtProject/tbclient/i18n/tbclient_zh.ts D:/QtProject/tbclient/tbclient.pro
	$(MAKE) -f $(MAKEFILE) qmake

tbclient_stub.pkg: D:/QtProject/tbclient/i18n/tbclient_zh.ts D:/QtProject/tbclient/tbclient.pro
	$(MAKE) -f $(MAKEFILE) qmake

sis: tbclient_template.pkg
	$(if $(wildcard .make.cache), $(MAKE) -f $(MAKEFILE) ok_sis MAKEFILES=.make.cache , $(if $(QT_SIS_TARGET), $(MAKE) -f $(MAKEFILE) ok_sis , $(MAKE) -f $(MAKEFILE) fail_sis_nocache ) )

ok_sis:
	D:\QtSDK\Symbian\SDKs\SymbianSR1Qt474\bin\createpackage.bat -g $(QT_SIS_OPTIONS) tbclient_template.pkg $(QT_SIS_TARGET) $(QT_SIS_CERTIFICATE) $(QT_SIS_KEY) $(QT_SIS_PASSPHRASE)

unsigned_sis: tbclient_template.pkg
	$(if $(wildcard .make.cache), $(MAKE) -f $(MAKEFILE) ok_unsigned_sis MAKEFILES=.make.cache , $(if $(QT_SIS_TARGET), $(MAKE) -f $(MAKEFILE) ok_unsigned_sis , $(MAKE) -f $(MAKEFILE) fail_sis_nocache ) )

ok_unsigned_sis:
	D:\QtSDK\Symbian\SDKs\SymbianSR1Qt474\bin\createpackage.bat -g $(QT_SIS_OPTIONS) -o tbclient_template.pkg $(QT_SIS_TARGET)

tbclient.sis:
	$(MAKE) -f $(MAKEFILE) sis

installer_sis: tbclient_installer.pkg sis
	$(MAKE) -f $(MAKEFILE) ok_installer_sis

ok_installer_sis: tbclient_installer.pkg
	D:\QtSDK\Symbian\SDKs\SymbianSR1Qt474\bin\createpackage.bat $(QT_SIS_OPTIONS) tbclient_installer.pkg - $(QT_SIS_CERTIFICATE) $(QT_SIS_KEY) $(QT_SIS_PASSPHRASE)

unsigned_installer_sis: tbclient_installer.pkg unsigned_sis
	$(MAKE) -f $(MAKEFILE) ok_unsigned_installer_sis

ok_unsigned_installer_sis: tbclient_installer.pkg
	D:\QtSDK\Symbian\SDKs\SymbianSR1Qt474\bin\createpackage.bat $(QT_SIS_OPTIONS) -o tbclient_installer.pkg

fail_sis_nocache:
	$(error Project has to be built or QT_SIS_TARGET environment variable has to be set before calling 'SIS' target)

stub_sis: tbclient_stub.pkg
	$(if $(wildcard .make.cache), $(MAKE) -f $(MAKEFILE) ok_stub_sis MAKEFILES=.make.cache , $(if $(QT_SIS_TARGET), $(MAKE) -f $(MAKEFILE) ok_stub_sis , $(MAKE) -f $(MAKEFILE) fail_sis_nocache ) )

ok_stub_sis:
	D:\QtSDK\Symbian\SDKs\SymbianSR1Qt474\bin\createpackage.bat -s $(QT_SIS_OPTIONS) tbclient_stub.pkg $(QT_SIS_TARGET) $(QT_SIS_CERTIFICATE) $(QT_SIS_KEY) $(QT_SIS_PASSPHRASE)

deploy: sis
	call tbclient.sis

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc\moc_tbsettings.cpp moc\moc_utility.cpp moc\moc_tbnetworkaccessmanagerfactory.cpp moc\moc_httpuploader.cpp moc\moc_scribbleArea.cpp moc\moc_customwebview.cpp moc\moc_downloader.cpp moc\moc_drmfile.cpp moc\moc_qiap.cpp moc\moc_qiap_p.cpp moc\moc_qvibra.cpp moc\moc_qmlapplicationviewer.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc\moc_tbsettings.cpp moc\moc_utility.cpp moc\moc_tbnetworkaccessmanagerfactory.cpp moc\moc_httpuploader.cpp moc\moc_scribbleArea.cpp moc\moc_customwebview.cpp moc\moc_downloader.cpp moc\moc_drmfile.cpp moc\moc_qiap.cpp moc\moc_qiap_p.cpp moc\moc_qvibra.cpp moc\moc_qmlapplicationviewer.cpp
moc\moc_tbsettings.cpp: src\tbsettings.h
	D:\QtSDK\Symbian\SDKs\SymbianSR1Qt474\bin\moc.exe $(DEFINES) $(INCPATH) -DSYMBIAN d:\QtProject\tbclient\src\tbsettings.h -o d:\QtProject\tbclient\moc\moc_tbsettings.cpp

moc\moc_utility.cpp: src\utility.h
	D:\QtSDK\Symbian\SDKs\SymbianSR1Qt474\bin\moc.exe $(DEFINES) $(INCPATH) -DSYMBIAN d:\QtProject\tbclient\src\utility.h -o d:\QtProject\tbclient\moc\moc_utility.cpp

moc\moc_tbnetworkaccessmanagerfactory.cpp: src\tbnetworkaccessmanagerfactory.h
	D:\QtSDK\Symbian\SDKs\SymbianSR1Qt474\bin\moc.exe $(DEFINES) $(INCPATH) -DSYMBIAN d:\QtProject\tbclient\src\tbnetworkaccessmanagerfactory.h -o d:\QtProject\tbclient\moc\moc_tbnetworkaccessmanagerfactory.cpp

moc\moc_httpuploader.cpp: src\httpuploader.h
	D:\QtSDK\Symbian\SDKs\SymbianSR1Qt474\bin\moc.exe $(DEFINES) $(INCPATH) -DSYMBIAN d:\QtProject\tbclient\src\httpuploader.h -o d:\QtProject\tbclient\moc\moc_httpuploader.cpp

moc\moc_scribbleArea.cpp: src\scribbleArea.h
	D:\QtSDK\Symbian\SDKs\SymbianSR1Qt474\bin\moc.exe $(DEFINES) $(INCPATH) -DSYMBIAN d:\QtProject\tbclient\src\scribbleArea.h -o d:\QtProject\tbclient\moc\moc_scribbleArea.cpp

moc\moc_customwebview.cpp: src\customwebview.h
	D:\QtSDK\Symbian\SDKs\SymbianSR1Qt474\bin\moc.exe $(DEFINES) $(INCPATH) -DSYMBIAN d:\QtProject\tbclient\src\customwebview.h -o d:\QtProject\tbclient\moc\moc_customwebview.cpp

moc\moc_downloader.cpp: src\downloader.h
	D:\QtSDK\Symbian\SDKs\SymbianSR1Qt474\bin\moc.exe $(DEFINES) $(INCPATH) -DSYMBIAN d:\QtProject\tbclient\src\downloader.h -o d:\QtProject\tbclient\moc\moc_downloader.cpp

moc\moc_drmfile.cpp: qiap\drmfile.h
	D:\QtSDK\Symbian\SDKs\SymbianSR1Qt474\bin\moc.exe $(DEFINES) $(INCPATH) -DSYMBIAN d:\QtProject\tbclient\qiap\drmfile.h -o d:\QtProject\tbclient\moc\moc_drmfile.cpp

moc\moc_qiap.cpp: qiap\qiap.h
	D:\QtSDK\Symbian\SDKs\SymbianSR1Qt474\bin\moc.exe $(DEFINES) $(INCPATH) -DSYMBIAN d:\QtProject\tbclient\qiap\qiap.h -o d:\QtProject\tbclient\moc\moc_qiap.cpp

moc\moc_qiap_p.cpp: qiap\qiap_p.h
	D:\QtSDK\Symbian\SDKs\SymbianSR1Qt474\bin\moc.exe $(DEFINES) $(INCPATH) -DSYMBIAN d:\QtProject\tbclient\qiap\qiap_p.h -o d:\QtProject\tbclient\moc\moc_qiap_p.cpp

moc\moc_qvibra.cpp: QVibra\qvibra.h
	D:\QtSDK\Symbian\SDKs\SymbianSR1Qt474\bin\moc.exe $(DEFINES) $(INCPATH) -DSYMBIAN d:\QtProject\tbclient\QVibra\qvibra.h -o d:\QtProject\tbclient\moc\moc_qvibra.cpp

moc\moc_qmlapplicationviewer.cpp: qmlapplicationviewer\qmlapplicationviewer.h
	D:\QtSDK\Symbian\SDKs\SymbianSR1Qt474\bin\moc.exe $(DEFINES) $(INCPATH) -DSYMBIAN d:\QtProject\tbclient\qmlapplicationviewer\qmlapplicationviewer.h -o d:\QtProject\tbclient\moc\moc_qmlapplicationviewer.cpp

compiler_rcc_make_all: rcc\qrc_tbclient.cpp
compiler_rcc_clean:
	-$(DEL_FILE) rcc\qrc_tbclient.cpp
rcc\qrc_tbclient.cpp: tbclient.qrc \
		i18n\tbclient_zh.qm
	d:\QtSDK\Symbian\SDKs\SymbianSR1Qt474\bin\rcc.exe -name tbclient d:\QtProject\tbclient\tbclient.qrc -o d:\QtProject\tbclient\rcc\qrc_tbclient.cpp

compiler_image_collection_make_all: ui\qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) ui\qmake_image_collection.cpp
compiler_moc_source_make_all: moc\httpuploader.moc
compiler_moc_source_clean:
	-$(DEL_FILE) moc\httpuploader.moc
moc\httpuploader.moc: src\httpuploader.h \
		src\httpuploader.cpp
	D:\QtSDK\Symbian\SDKs\SymbianSR1Qt474\bin\moc.exe $(DEFINES) $(INCPATH) -DSYMBIAN d:\QtProject\tbclient\src\httpuploader.cpp -o d:\QtProject\tbclient\moc\httpuploader.moc

compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_moc_source_clean 

dodistclean:
	-@ if EXIST "d:\QtProject\tbclient\tbclient_template.pkg" $(DEL_FILE)  "d:\QtProject\tbclient\tbclient_template.pkg"
	-@ if EXIST "d:\QtProject\tbclient\tbclient_stub.pkg" $(DEL_FILE)  "d:\QtProject\tbclient\tbclient_stub.pkg"
	-@ if EXIST "d:\QtProject\tbclient\tbclient_installer.pkg" $(DEL_FILE)  "d:\QtProject\tbclient\tbclient_installer.pkg"
	-@ if EXIST "d:\QtProject\tbclient\Makefile" $(DEL_FILE)  "d:\QtProject\tbclient\Makefile"
	-@ if EXIST "d:\QtProject\tbclient\tbclient_exe.mmp" $(DEL_FILE)  "d:\QtProject\tbclient\tbclient_exe.mmp"
	-@ if EXIST "d:\QtProject\tbclient\tbclient_reg.rss" $(DEL_FILE)  "d:\QtProject\tbclient\tbclient_reg.rss"
	-@ if EXIST "d:\QtProject\tbclient\tbclient.rss" $(DEL_FILE)  "d:\QtProject\tbclient\tbclient.rss"
	-@ if EXIST "d:\QtProject\tbclient\tbclient.loc" $(DEL_FILE)  "d:\QtProject\tbclient\tbclient.loc"
	-@ if EXIST "d:\QtProject\tbclient\bld.inf" $(DEL_FILE)  "d:\QtProject\tbclient\bld.inf"

distclean: clean dodistclean

clean: bld.inf
	-$(SBS) reallyclean --toolcheck=off -c winscw_udeb.mwccinc -c arm.v5.udeb.gcce4_4_1 -c arm.v6.udeb.gcce4_4_1 -c arm.v5.urel.gcce4_4_1 -c arm.v6.urel.gcce4_4_1


